### ISSUE TITLE
When would I use this?

### ISSUE THREAD

**Issue by Feel-ix-343** [JojoMakesGames/git-remote-url.nvim#1]
Im interested

**Comment by JojoMakesGames** [comment]
The use case I have for it is when I'm sharing an issue in some repo with a coworker. It's much easier to just link to the file in github rather than say which file/line number. This way I just go to the code in my editor that I'm working on, press `<leader>yg` and they will get the current file and line number on the main branch of that repo

**Comment by Feel-ix-343** [comment]
oh very neat. Thank you.
